.\" Manpage for nuseradd.
.\" Contact linarcx@riseup.net to correct errors or typos.
.TH man 7 "17 Aug 2019" "1.0" "linarcx vim configs man page"
.SH NAME
linvim \- linarcx vim configurations
.SH DESCRIPTION
I try to explain more about my configurations in neovim.
.SH BUGS
https://github.com/LinArcX/VoidConf/issues
.SH AUTHOR
LinArcX (linarcx@riseup.net)

